Repository odoo-dev/jabberwock, pull requests merged in 2020-09, with the labels that each got.

#352 [IMP] OdooWebsiteEditor: adapt for odoo mass_mailing.
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
  packages/bundle-odoo-website-editor/odoo-integration.ts
  packages/plugin-dom-editable/src/DomEditable.ts
  packages/plugin-html/src/DefaultHtmlTextParser.ts
  packages/plugin-template/src/Template.ts
Labels: ready to merge... now!

#353 [FIX] DomEditable: encapsulate _matchCommand
  packages/plugin-dom-editable/src/DomEditable.ts
Labels: awaiting review

#355 [IMP] odooWebsiteEditor: allow to edit source as string
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
Labels: ready to merge... now!

#357 [FIX] OdooWebsiteEditor: add editable zone to facilitate integration
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
  packages/plugin-theme/src/ThemeNode.ts
Labels: ready to merge... now!

#358 [IMP] Iframe,OdooWebsiteEditor: better iframe event forwarding
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
  packages/plugin-dom-helpers/src/DomHelpers.ts
  packages/plugin-iframe/src/IframeDomObjectRenderer.ts
  packages/utils/src/polyfill.ts
Labels: awaiting review, ready to merge... now!

#359 [FIX] XML: fix style parsing
  packages/plugin-xml/src/CssStyle.ts
Labels: awaiting review

#361 [FIX] Odoo: remove unused ts file when building
  package.json
Labels: awaiting review

#362 [IMP] Devtool: Allow to select text inside devtool
  packages/plugin-devtools/assets/DevTools.css
Labels: awaiting review

#363 [IMP] Renderer: throw error when missing engine id
  packages/plugin-renderer/src/Renderer.ts
Labels: awaiting review

#354 [FIX] FontSize: remove duplicated logic for input
  packages/plugin-font-size/src/FontSizeDomObjectRenderer.ts
Labels: awaiting review

#366 [FIX] Table: Only show insert Table button in Text content
  packages/plugin-table/src/Table.ts
Labels: ready to merge... now!

#368 [FIX] OdooWebsiteEditor: ensure editor has editable content
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
Labels: awaiting review

#370 [FIX] EventNormalizer: do not select all on dbclick first word
  packages/plugin-dom-editable/src/EventNormalizer.ts
  packages/plugin-dom-editable/test/EventNormalizerPointer.test.ts
Labels: awaiting review

#351 [IMP] Odoo: add dropdown on top of table
  packages/plugin-image/src/ImageDomObjectRenderer.ts
  packages/plugin-odoo/src/Odoo.ts
  packages/plugin-odoo/src/OdooTableDomObjectRenderer.ts
  packages/plugin-table/assets/tableEdit.xml
  packages/plugin-table/assets/tableUI.css
  packages/plugin-table/src/TableCellDomObjectRenderer.ts
  packages/plugin-table/src/TableDomObjectRenderer.ts
  packages/utils/src/Positionable.ts
Labels: awaiting review

#372 [FIX] Core: applyFormat everything
  packages/core/test/VDocument.test.ts
  packages/plugin-inline/src/FormatXmlDomParser.ts
  packages/plugin-link/src/LinkXmlDomParser.ts
  packages/plugin-mail/test/Mail.test.ts
  packages/plugin-mail/test/testMailResult.xml
  packages/plugin-pre/test/Pre.test.ts
Labels: awaiting review

#375 [FIX] Parser: type ParserConstructor properly
  packages/plugin-parser/src/ParsingEngine.ts
Labels: awaiting review

#374 [IMP] Odoo: add button to default toolbar
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
Labels: awaiting review

#378 [FIX] OdooWebsiteEditor: getValue return the editable zone rendering
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
Labels: awaiting review

#380 Master fix mass mailing chm
  packages/plugin-fontawesome/src/FontAwesomeMailObjectRenderer.ts
  packages/plugin-image/src/ImageMailObjectRenderer.ts
  packages/plugin-mail/src/MailObjectRenderingEngine.ts
  packages/plugin-mail/test/testMailBase.xml
  packages/plugin-mail/test/testMailResult.xml
  packages/plugin-theme/src/ThemeDomObjectRenderer.ts
Labels: awaiting review, ready to merge... now!

#382 [FIX] Memory: exact index of changes in the list regardless of the size
  packages/core/src/Memory/Memory.ts
  packages/core/src/Memory/test/memory.test.ts
  packages/plugin-dom-layout/src/DomReconciliationEngine.ts
  packages/plugin-linebreak/test/LineBreak.test.ts
Labels: awaiting review, ready to merge... now!

#383 [IMP] DomEditable: remove useless code and add tests.
  packages/core/src/Memory/test/memory.test.ts
  packages/plugin-dom-editable/src/MutationNormalizer.ts
  packages/plugin-dom-editable/test/MutationNormalizer.test.ts
Labels: awaiting review

#384 [IMP] JWEditor: execCommand return the error message for failed commands
  packages/core/src/JWEditor.ts
  packages/core/test/JWeditor.test.ts
  packages/core/test/Mode.test.ts
  packages/core/test/VDocument.test.ts
  packages/plugin-align/test/Align.test.ts
  packages/plugin-dom-editable/test/DomEditable.test.ts
  packages/plugin-dom-helpers/src/DomHelpers.ts
  packages/plugin-dom-layout/test/DomLayout.test.ts
  packages/plugin-font-size/test/FontSize.test.ts
  packages/plugin-fontawesome/test/FontAwesome.test.ts
  packages/plugin-heading/test/Heading.test.ts
  packages/plugin-indent/test/Indent.test.ts
  packages/plugin-inline/test/Inline.test.ts
  packages/plugin-linebreak/src/LineBreak.ts
  packages/plugin-linebreak/test/LineBreak.test.ts
  packages/plugin-link/src/Link.ts
  packages/plugin-list/src/ListDomObjectRenderer.ts
  packages/plugin-list/test/List.test.ts
  packages/plugin-odoo/src/Odoo.ts
  packages/plugin-odoo/src/OdooTableDomObjectRenderer.ts
  packages/plugin-pre/test/Pre.test.ts
  packages/plugin-table/test/Table.test.ts
Labels: awaiting review

#381 [FIX] FontAwesome: remove params from fontawesome
  packages/plugin-odoo/src/OdooFontAwesomeDomObjectRenderer.ts
Labels: awaiting review

#387 [FIX] DomEditable: normalization should work in shadow for all browser
  packages/plugin-dom-editable/src/EventNormalizer.ts
  packages/plugin-dom-layout/src/DomLayout.ts
  packages/plugin-iframe/test/iframe.test.ts
Labels: awaiting review

#389 [FIX] Html: should parse xml invalid attributes (with < and >)
  packages/plugin-html/src/DefaultHtmlTextParser.ts
  packages/plugin-html/test/DefaultDomRenderer.test.ts
Labels: awaiting review

#390 [FIX] DomLayout: should never have a taceback with altered DOM
  packages/plugin-dom-layout/src/DomReconciliationEngine.ts
Labels: awaiting review

#388 [FIX] Iframe: Parse and render non editable iframe
  packages/plugin-iframe/src/IframeDomObjectRenderer.ts
  packages/plugin-iframe/src/IframeHtmlDomParser.ts
  packages/plugin-iframe/src/IframeNode.ts
Labels: awaiting review

#391 [FIX] DomLayout,History: undo/redo should redraw all old removed nodes
  packages/plugin-dom-layout/src/DomLayoutEngine.ts
  packages/plugin-history/src/History.ts
  packages/plugin-history/test/History.test.ts
Labels: awaiting review

#392 [IMP] Odoo: add information when change
  packages/plugin-odoo-field/src/OdooField.ts
  packages/plugin-odoo/src/OdooStructureNode.ts
Labels: awaiting review

#393 [FIX] Odoo: check if containernode dirty
  packages/plugin-odoo/src/OdooStructureNode.ts
  packages/plugin-odoo/src/OdooStructureXmlDomParser.ts
Labels: awaiting review

#395 [FIX] Export FontAwesomeNode to fix a traceback in odoo media modal
  packages/bundle-odoo-website-editor/odoo-integration.ts
Labels: ready to merge... now!

#396 [FIX] Table: set default value if undefined
  packages/plugin-table/src/TableCellMailObjectRenderer.ts
Labels: awaiting review

#397 [FIX] Template: should display the label in place when scroll down
  packages/plugin-template/assets/Template.css
Labels: awaiting review, ready to merge... now!

#398 [FIX] Fontawesome,Metadata: implement clone
  packages/plugin-fontawesome/src/FontAwesomeNode.ts
  packages/plugin-metadata/src/MetadataNode.ts
Labels: awaiting review

#399 [IMP] Odoo: change target to es8 (es2017)
  package.json
Labels: awaiting review

#400 [FIX] Odoo: do not parse some translation node
  packages/plugin-odoo/src/OdooTranslationXmlDomParser.ts
Labels: awaiting review

#401 [IMP] DomHelper: add text command
  packages/plugin-dom-helpers/src/DomHelpers.ts
Labels: awaiting review

#406 [FIX] Iframe: add id on the body inside css, to allow custom style.
  packages/plugin-iframe/src/IframeDomObjectRenderer.ts
Labels: ready to merge... now!

#408 [IMP] Odoo: add toolbar component for icons (font-awsome)
  packages/plugin-odoo/src/Odoo.ts
Labels: awaiting review

#409 [FIX] Odoo: select the image padding into the toolbar
  packages/plugin-odoo/src/Odoo.ts
Labels: awaiting review

#410 [FIX] FontSize: display the font-size with range on end container.
  packages/plugin-font-size/src/FontSizeDomObjectRenderer.ts
Labels: awaiting review

#407 [IMP] Toolbar: add groupname to actionables config
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
  packages/plugin-dom-layout/src/ActionableGroupDomObjectRenderer.ts
  packages/plugin-layout/src/ActionableGroupNode.ts
  packages/plugin-theme/test/Theme.test.ts
  packages/plugin-toolbar/src/Toolbar.ts
  packages/plugin-toolbar/src/ToolbarXmlDomParser.ts
  packages/plugin-toolbar/test/toolbar.test.ts
Labels: awaiting review

#412 [FIX] Layout: remove type error on example
  examples/layout/layout.ts
Labels: awaiting review

#416 [FIX] Layout: remove extra parenthesis
  examples/layout/layout.ts
Labels: ready to merge... now!

#415 [IMP] Odoo: sidebar to the right
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
Labels: awaiting review

#418 [IMP] Change the way the colorpicker behave in Odoo
  packages/bundle-odoo-website-editor/odoo-integration.ts
  packages/plugin-odoo/src/Odoo.ts
Labels: ready to merge... now!

#419 [FIX] Odoo: add align button with classes for image and icon font-awsome
  packages/plugin-odoo/src/Odoo.ts
Labels: awaiting review

#423 [FIX] Link: should apply link format on the selection or replace content
  packages/plugin-link/assets/LinkForm.xml
  packages/plugin-link/src/Link.ts
  packages/plugin-link/src/components/LinkComponent.ts
  packages/plugin-link/test/Link.test.ts
Labels: awaiting review

#424 Master fix icon color chm
  packages/plugin-odoo/src/Odoo.ts
Labels: ready to merge... now!

#427 Master fix recon chm
  packages/plugin-dom-layout/src/DomReconciliationEngine.ts
  packages/plugin-dom-layout/test/DomLayout.test.ts
  packages/plugin-list/test/List.test.ts
Labels: awaiting review

#425 [FIX] Odoo: insertMedia keep previous modifiers
  packages/plugin-odoo/src/Odoo.ts
Labels: awaiting review
