Repository odoo-dev/jabberwock, pull requests merged in 2020-08, with the labels that each got.

#269 [ADD] Code: view and edit the document's html
  packages/bundle-basic-editor/BasicEditor.ts
  packages/plugin-code/src/Code.ts
  packages/plugin-code/src/CodeButtonDomObjectRenderer.ts
  packages/plugin-code/src/CodeViewDomObjectRenderer.ts
  packages/plugin-code/src/CodeViewNode.ts
Labels: awaiting review

#270 [IMP] FollowRange : more robust positioning for the floating toolbar
  packages/plugin-dom-follow-range/src/FollowRangeZoneDomObjectRenderer.ts
Labels: wip

#276 [IMP] Remove styles from Toolbar
  examples/demo-odoo-fields/demo-odoo-fields.ts
  examples/demo/demo.ts
  examples/jabberwockipedia/jabberwockipedia.ts
  examples/jabberwocky/jabberwocky.ts
  examples/layout/layout.ts
  examples/modes/modes.ts
  examples/odoo/odoo.ts
  examples/resizable/resizable.ts
  packages/plugin-toolbar/src/Toolbar.ts
Labels: awaiting review

#275 [IMP] OdooWebsiteEditor: remove unnecessary config
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
Labels: awaiting review

#274 [CLEAN] MediaDialog: remove artefact code
  packages/plugin-media-dialog/assets/Toolbar.css
  packages/plugin-media-dialog/assets/Toolbar.xml
Labels: awaiting review

#273 [FIX] FollowRange: prevent toolbar hide on click
  packages/plugin-dom-follow-range/src/FollowRangeZoneDomObjectRenderer.ts
  packages/plugin-dom-layout/src/ActionableDomObjectRenderer.ts
Labels: awaiting review

#280 [FIX] Html: cannot attach a domNode to a property
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
  packages/plugin-html/src/HtmlNode.ts
  packages/plugin-html/src/HtmlNodeDomRenderer.ts
Labels: awaiting review

#281 [FIX] DomHelper: use execCommand
  packages/plugin-dom-helpers/src/DomHelpers.ts
Labels: awaiting review

#282 [IMP] *: Very significant speed improvement.
  packages/plugin-align/src/Align.ts
  packages/plugin-bold/src/Bold.ts
  packages/plugin-heading/src/Heading.ts
  packages/plugin-italic/src/Italic.ts
  packages/plugin-list/src/List.ts
  packages/plugin-pre/src/Pre.ts
  packages/plugin-underline/src/Underline.ts
Labels: ready to merge... now!

#284 [IMP] Odoo integration: make default port 8080
  dev/odoo-integration-dev.js
Labels: awaiting review

#286 [FIX] Layout/History: attach Layout component to memory + fix cache
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
  packages/core/test/ContextManager.test.ts
  packages/core/test/JWeditor.test.ts
  packages/core/test/VDocument.test.ts
  packages/core/test/VNodes.test.ts
  packages/core/test/VRange.test.ts
  packages/plugin-align/test/Align.test.ts
  packages/plugin-code/src/Code.ts
  packages/plugin-devtools/src/components/InspectorComponent.ts
  packages/plugin-devtools/test/devtools.test.ts
  packages/plugin-dialog/src/DialogZoneDomObjectRenderer.ts
  packages/plugin-dialog/test/Dialog.test.ts
  packages/plugin-dom-editable/src/DomEditable.ts
  packages/plugin-dom-layout/src/DomLayoutEngine.ts
  packages/plugin-dom-layout/test/DomLayout.test.ts
  packages/plugin-fullscreen/src/FullscreenButtonDomObjectRenderer.ts
  packages/plugin-history/test/History.test.ts
  packages/plugin-indent/test/Indent.test.ts
  packages/plugin-keymap/test/Keymap.test.ts
  packages/plugin-layout/src/LayoutEngine.ts
  packages/plugin-list/test/List.test.ts
  packages/plugin-parser/test/Parser.test.ts
  packages/plugin-shadow/test/DomShadow.test.ts
  packages/plugin-table/src/TablePickerDomObjectRenderer.ts
  packages/plugin-table/test/Table.test.ts
  packages/utils/src/testUtils.ts
  packages/utils/test/testUtils.test.ts
Labels: ready to merge... now!

#285 [ADD] DomEditable: implement deleteWord
  packages/core/src/Core.ts
  packages/plugin-dom-editable/src/DomEditable.ts
  packages/plugin-dom-editable/src/MutationNormalizer.ts
Labels: awaiting review

#287 [FIX] Iframe: add test and fix example
  examples/layout/main.xml
  packages/plugin-iframe/test/iframe.test.ts
Labels: awaiting review, ready to merge... now!

#289 [FIX] remove afterRender hook
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
Labels: awaiting review

#290 [FIX] Color: properly apply colors on nodes and their formats
  packages/plugin-color/src/Color.ts
  packages/plugin-textcolor/test/TextColor.test.ts
Labels: awaiting review

#292 [IMP] DomHelper: introduce ExecutionContext
  packages/plugin-dom-helpers/src/DomHelpers.ts
Labels: awaiting review

#293 [FIX] DomLayout: altered dom must be invalidate from the generated dom.
  packages/plugin-dom-layout/src/DomReconciliationEngine.ts
  packages/plugin-dom-layout/test/DomLayout.test.ts
Labels: awaiting review

#291 deadlock detection
  packages/core/src/JWEditor.ts
Labels: awaiting review

#294 [FIX] EventNormalizer: handle double and triple clicks with nested nodes
  packages/plugin-dom-editable/src/EventNormalizer.ts
  packages/plugin-dom-editable/test/EventNormalizerPointer.test.ts
Labels: awaiting review

#295 [FIX] FontAwesome: remove FontAwesome classes on parsing
  packages/plugin-fontawesome/src/FontAwesomeDomObjectRenderer.ts
  packages/plugin-fontawesome/src/FontAwesomeNode.ts
  packages/plugin-fontawesome/src/FontAwesomeXmlDomParser.ts
  packages/plugin-fontawesome/test/FontAwesome.test.ts
  packages/plugin-xml/src/AttributesDomObjectModifierRenderer.ts
  packages/plugin-xml/src/ClassList.ts
Labels: awaiting review

#296 [FIX] Core: VRange is collapsed if the selection contains only untang…
  packages/core/src/VRange.ts
  packages/core/test/VDocument.test.ts
  packages/core/test/VRange.test.ts
  packages/plugin-dom-editable/test/DomEditableBasicEditor.test.ts
Labels: awaiting review

#298 [FIX] DomLayout: Can redraw an altered text node without content.
  packages/plugin-dom-layout/src/DomReconciliationEngine.ts
  packages/plugin-dom-layout/test/DomLayout.test.ts
Labels: awaiting review, ready to merge... now!

#303 [IMP] OdooWebsite: add theme: mobile preview
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
  packages/bundle-odoo-website-editor/odooLayout.css
  packages/plugin-html/src/DefaultHtmlTextParser.ts
  packages/plugin-iframe/src/IframeDomObjectRenderer.ts
Labels: ready to merge... now!

#308 [FIX] DomReconciliationEngine: set range on trailing lineBreak
  packages/plugin-dom-layout/src/DomReconciliationEngine.ts
  packages/plugin-dom-layout/test/DomLayout.test.ts
Labels: awaiting review

#311 [FIX] DomLayout: don't try to redraw item previously removed.
  packages/plugin-dom-layout/src/DomLayoutEngine.ts
  packages/plugin-dom-layout/test/DomLayout.test.ts
Labels: awaiting review

#309 [CLEAN] unused import
  packages/plugin-dom-editable/test/eventNormalizerUtils.ts
Labels: awaiting review

#314 [IMP] DomLayout: add tests for render selection
  packages/plugin-dom-layout/test/DomLayout.test.ts
Labels: ready to merge... now!

#316 [IMP] DomHelpers: remove class on format modifiers.
  packages/plugin-dom-helpers/src/DomHelpers.ts
Labels: awaiting review

#320 [FIX] LineBreak: do not parse a placeholder BR with formatting space
  packages/plugin-linebreak/src/LineBreakXmlDomParser.ts
  packages/plugin-linebreak/test/LineBreak.test.ts
  packages/utils/src/Dom.ts
  packages/utils/src/testUtils.ts
Labels: awaiting review

#328 [IMP] Odoo: Add image description
  packages/plugin-odoo/src/Odoo.ts
Labels: awaiting review

#327 [FIX] Odoo: wrap only inlineNode
  packages/plugin-odoo/src/NoteEditableXmlDomParser.ts
  packages/plugin-odoo/src/Odoo.ts
Labels: awaiting review

#333 [FIX] Heading: restrict applyHeadingStyle
  packages/plugin-heading/src/Heading.ts
  packages/plugin-heading/test/Heading.test.ts
Labels: awaiting review

#341 [FIX] DomLayout: pressing enter creates <p></p> without <br/>; + sele…
  packages/core/test/VDocument.test.ts
  packages/plugin-dom-editable/src/DomEditable.ts
  packages/plugin-dom-editable/test/DomEditable.test.ts
  packages/plugin-dom-layout/src/DomReconciliationEngine.ts
  packages/plugin-shadow/test/DomShadow.test.ts
Labels: awaiting review

#342 [FIX] Table: properly trigger commands on click table buttons
  packages/plugin-table/src/TableCellDomObjectRenderer.ts
Labels: awaiting review

#345 [IMP] Remove font format when applyHeadingStyle
  packages/plugin-odoo/src/Odoo.ts
Labels: awaiting review

#347 [IMP] Odoo: shortcut link openLinkDialog
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
Labels: awaiting review

#348 [REF] MediaDialog: Remove code artefact
  packages/plugin-media-dialog/src/MediaDialog.ts
Labels: awaiting review

#343 Master rollup nby
  package.json
  packages/bundle-basic-editor/BasicEditor.ts
  packages/bundle-odoo-website-editor/odoo-integration.ts
  rollup.config.js
  tsconfig.json
Labels: awaiting review
