Repository odoo-dev/jabberwock, pull requests merged in 2020-10, with the labels that each got.

#431 [IMP] Fontawesome: only surround fa when close to range
  packages/plugin-dom-layout/test/DomLayout.test.ts
  packages/plugin-fontawesome/src/FontAwesomeDomObjectRenderer.ts
  packages/plugin-fontawesome/test/FontAwesome.test.ts
  packages/plugin-odoo/src/OdooFontAwesomeDomObjectRenderer.ts
Labels: awaiting review

#433 [FIX] Iframe: discriminate IframeContainerNode
  packages/plugin-iframe/src/Iframe.ts
  packages/plugin-iframe/src/IframeContainerDomObjectRenderer.ts
  packages/plugin-iframe/src/IframeContainerNode.ts
  packages/plugin-iframe/src/IframeDomObjectRenderer.ts
  packages/plugin-iframe/src/IframeHtmlDomParser.ts
  packages/plugin-iframe/src/IframeNode.ts
  packages/plugin-iframe/src/IframeXmlDomParser.ts
  packages/plugin-iframe/test/iframe.test.ts
  packages/plugin-youtube/src/YoutubeXmlDomParser.ts
Labels: awaiting review

#436 [FIX] DomHelpers: Attributes depends on node
  packages/plugin-dom-helpers/src/DomHelpers.ts
Labels: awaiting review

#437 [IMP] Add OdooVideoNode in Odoo export
  packages/bundle-odoo-website-editor/odoo-integration.ts
Labels: ready to merge... now!

#435 [FIX] AbstractNode: check contenteditable attribute on formats too
  packages/core/src/JWEditor.ts
  packages/core/src/VNodes/AbstractNode.ts
  packages/plugin-dom-layout/src/DomLayout.ts
  packages/plugin-fontawesome/src/FontAwesomeDomObjectRenderer.ts
  packages/plugin-fontawesome/test/FontAwesome.test.ts
  packages/utils/src/utils.ts
Labels: awaiting review

#434 [IMP] DomLayout,Toolbar: can render select into block to apply css
  examples/layout/layout.ts
  packages/plugin-dom-layout/src/ActionableDomObjectRenderer.ts
  packages/plugin-dom-layout/src/ActionableGroupDomObjectRenderer.ts
  packages/plugin-dom-layout/src/DomLayout.ts
  packages/plugin-dom-layout/test/DomLayout.test.ts
  packages/plugin-native-select/src/NativeSelect.ts
  packages/plugin-native-select/src/NativeSelectActionableGroupDomObjectRenderer.ts
  packages/plugin-native-select/src/NativeSelectVNodeDomObjectRenderer.ts
  packages/plugin-template/test/Template.test.ts
  packages/plugin-toolbar/assets/Toolbar.css
  packages/plugin-toolbar/test/toolbar.test.ts
Labels: awaiting review, ready to merge... now!

#438 [FIX] DomLayout: don't change focus when edit an input or a textarea
  packages/plugin-dom-layout/src/DomLayoutEngine.ts
Labels: awaiting review, ready to merge... now!

#440 [FIX] OdooWebsiteEditor: Add class used by mass_mailing snippets
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
Labels: awaiting review, ready to merge... now!

#448 [FIX] Odoo: open the media modal in the right tab on dblclick media
  packages/plugin-odoo-video/src/OdooVideoDomObjectRenderer.ts
  packages/plugin-odoo/src/OdooFontAwesomeDomObjectRenderer.ts
  packages/plugin-odoo/src/OdooImageDomObjectRenderer.ts
Labels: awaiting review

#449 master-bundler-css-nby
  package-lock.json
  package.json
  rollup.config.js
Labels: awaiting review

#442 master-typo-dom-nby
  packages/plugin-renderer-dom-object/src/DomObjectRenderingEngine.ts
Labels: awaiting review

#450 [FIX] EventNormalizer: consistently apply insertLineBreak on shift+enter
  packages/plugin-dom-editable/src/EventNormalizer.ts
Labels: awaiting review

#452 [FIX] formattingSpace: remove space between inline elem and block
  packages/utils/src/formattingSpace.ts
  packages/utils/test/formattingSpace.test.ts
Labels: awaiting review

#454 [FIX] Template: ensure an overflow on the template container
  packages/plugin-template/assets/Template.css
Labels: awaiting review

#458 [FIX] EventNormalizer: Don't force a line break with [any key] + [ENTER]
  packages/plugin-dom-editable/src/EventNormalizer.ts
Labels: ready to merge... now!

#457 [ADD] DomHelpers: set class helper
  packages/plugin-dom-helpers/src/DomHelpers.ts
Labels: awaiting review, wip

#455 [FIX] formattingSpace: properly ignore empty text and hidden inputs.
  packages/utils/src/formattingSpace.ts
  packages/utils/src/isBlock.ts
  packages/utils/test/formattingSpace.test.ts
Labels: awaiting review

#462 [FIX] List: Keep lonely containers in LI if they have attribute(s)
  packages/plugin-list/src/ListItemXmlDomParser.ts
  packages/plugin-list/test/List.test.ts
Labels: awaiting review
