Repository odoo-dev/jabberwock, pull requests merged in 2020-05, with the labels that each got.

#159 [IMP] change id reference for parser and renderer
  packages/core/test/VNodes.test.ts
  packages/plugin-blockquote/src/BlockquoteXmlDomParser.ts
  packages/plugin-bold/src/BoldXmlDomParser.ts
  packages/plugin-char/src/CharFormatHtmlDomRenderer.ts
  packages/plugin-char/src/CharHtmlDomRenderer.ts
  packages/plugin-char/src/CharXmlDomParser.ts
  packages/plugin-divider/src/DividerXmlDomParser.ts
  packages/plugin-dom-layout/src/ui/LayoutContainerHtmlDomRenderer.ts
  packages/plugin-dom-layout/src/ui/ZoneHtmlDomRenderer.ts
  packages/plugin-dom-layout/src/ui/ZoneXmlDomParser.ts
  packages/plugin-dom-layout/test/DomLayout.test.ts
  packages/plugin-fontawesome/src/FontAwesomeHtmlDomRenderer.ts
  packages/plugin-fontawesome/src/FontAwesomeXmlDomParser.ts
  packages/plugin-heading/src/HeadingXmlDomParser.ts
  packages/plugin-html/src/DefaultHtmlDomParser.ts
  packages/plugin-image/src/ImageHtmlDomRenderer.ts
  packages/plugin-image/src/ImageXmlDomParser.ts
  packages/plugin-inline/src/InlineFormatDomRenderer.ts
  packages/plugin-italic/src/ItalicXmlDomParser.ts
  packages/plugin-linebreak/src/LineBreakHtmlDomRenderer.ts
  packages/plugin-linebreak/src/LineBreakXmlDomParser.ts
  packages/plugin-link/src/LinkXmlDomParser.ts
  packages/plugin-list/src/ListHtmlDomRenderer.ts
  packages/plugin-list/src/ListItemHtmlDomRenderer.ts
  packages/plugin-list/src/ListItemXmlDomParser.ts
  packages/plugin-list/src/ListXmlDomParser.ts
  packages/plugin-metadata/src/MetaDataHtmlDomRenderer.ts
  packages/plugin-metadata/src/MetadataXmlDomParser.ts
  packages/plugin-owl/src/ui/OwlHtmlDomRenderer.ts
  packages/plugin-paragraph/src/ParagraphXmlDomParser.ts
  packages/plugin-pre/src/PreHtmlDomRenderer.ts
  packages/plugin-pre/src/PreXmlDomParser.ts
  packages/plugin-span/src/SpanXmlDomParser.ts
  packages/plugin-subscript/src/SubscriptXmlDomParser.ts
  packages/plugin-superscript/src/SuperscriptXmlDomParser.ts
  packages/plugin-table/src/TableCellHtmlDomRenderer.ts
  packages/plugin-table/src/TableCellXmlDomParser.ts
  packages/plugin-table/src/TableHtmlDomRenderer.ts
  packages/plugin-table/src/TableRowHtmlDomRenderer.ts
  packages/plugin-table/src/TableRowXmlDomParser.ts
  packages/plugin-table/src/TableXmlDomParser.ts
  packages/plugin-underline/src/UnderlineXmlDomParser.ts
  packages/plugin-youtube/src/YoutubeHtmlDomRenderer.ts
  packages/plugin-youtube/src/YoutubeXmlDomParser.ts
Labels: awaiting review

#166 [REF] VNode: add a method to replace a node with another
  packages/core/src/VNodes/AbstractNode.ts
  packages/plugin-heading/src/Heading.ts
  packages/plugin-list/src/List.ts
  packages/plugin-pre/src/Pre.ts
Labels: awaiting review, ready to merge... now!

#168 [IMP] OdooVideo: parse/render odoo video
  examples/odoo/index.html
  examples/odoo/odoo.ts
  examples/odoo/odoo.xml
  examples/utils/editor.css
  packages/plugin-odoo-video/src/OdooVideo.ts
  packages/plugin-odoo-video/src/OdooVideoHtmlDomRenderer.ts
  packages/plugin-odoo-video/src/OdooVideoNode.ts
  packages/plugin-odoo-video/src/OdooVideoXmlDomParser.ts
  packages/plugin-odoo-video/test/OdooVideo.test.ts
Labels: awaiting review

#157 Master fix selection without root nby
  packages/plugin-dom-layout/test/DomLayout.test.ts
Labels: awaiting review

#173 [FIX] Link: prevent the toolbar from crashing on click in empty element
  packages/plugin-link/src/LinkButtons.ts
Labels: awaiting review

#174 [FIX] Link: ensure link dialog fully closes on save
  packages/plugin-link/src/components/LinkComponent.ts
Labels: awaiting review

#178 remove memory leak and wrong unbinding
  packages/plugin-devtools/src/components/DevToolsComponent.ts
  packages/plugin-devtools/src/components/InspectorComponent.ts
  packages/plugin-devtools/test/devtools.test.ts
  packages/plugin-dom-editable/src/EventNormalizer.ts
  packages/plugin-owl/src/Owl.ts
  packages/plugin-owl/src/ui/OwlHtmlDomRenderer.ts
Labels: needs refactoring

#184 [FIX] Owl: bump version and add env browser
  package.json
  packages/plugin-owl/src/Owl.ts
Labels: awaiting review

#186 Master fix owl2 nby
  packages/plugin-owl/src/Owl.ts
Labels: awaiting review
