Repository odoo-dev/jabberwock, pull requests merged in 2020-06, with the labels that each got.

#196 [FIX] VNode: empty VNode properly
  packages/core/src/VNodes/ContainerNode.ts
  packages/core/test/VNodes.test.ts
Labels: awaiting review

#200 fixes
  packages/plugin-dom-layout/src/ui/DomReconciliationEngine.ts
  packages/plugin-dom-layout/test/DomLayout.test.ts
  packages/plugin-html/src/DefaultDomObjectRenderer.ts
Labels: awaiting review

#201 [FIX] dom-layout: long press bacspace can create an altered
  packages/plugin-dom-layout/src/ui/DomReconciliationEngine.ts
  packages/plugin-dom-layout/test/DomLayout.test.ts
Labels: awaiting review, ready to merge... now!

#182 [IMP] DomEditable is free of components
  bundles/BasicEditor.ts
  examples/demo/demo.ts
  examples/jabberwockipedia/jabberwockipedia.ts
  examples/jabberwocky/jabberwocky.ts
  examples/layout/layout.ts
  examples/odoo/odoo.ts
  packages/core/test/VNodes.test.ts
  packages/plugin-devtools/test/devtools.test.ts
  packages/plugin-dom-editable/src/DomEditable.ts
  packages/plugin-dom-editable/test/DomEditable.test.ts
  packages/plugin-dom-follow-range/test/FollowRange.test.ts
  packages/plugin-dom-layout/src/ui/DomLayoutEngine.ts
  packages/plugin-dom-layout/test/DomLayout.test.ts
  packages/plugin-keymap/test/Keymap.test.ts
  packages/plugin-parser/test/Parser.test.ts
  packages/plugin-shadow/test/DomShadow.test.ts
  packages/utils/src/DomMap.ts
  packages/utils/src/configuration.ts
  packages/utils/src/testUtils.ts
Labels: awaiting review, ready to merge... now!

#211 [FIX] followRange: Follow the range in the shadow dom.
  examples/layout/layout.ts
  packages/plugin-dom-follow-range/src/FollowRangeZoneDomObjectRenderer.ts
  packages/plugin-dom-follow-range/test/FollowRange.test.ts
  packages/utils/src/testUtils.ts
Labels: awaiting review

#212 [IMP] DomLayout: shadowRoot ca be add from domObject.
  packages/plugin-dom-layout/src/ui/DomReconciliationEngine.ts
  packages/plugin-html/src/DomObjectRenderingEngine.ts
  packages/plugin-shadow/src/ShadowDomObjectRenderer.ts
  packages/utils/src/polyfill.ts
Labels: awaiting review

#223 [FIX] Toolbar: button order don't depends of the plugin loading
  packages/plugin-toolbar/src/Toolbar.ts
Labels: awaiting review

#228 [FIX] odoo image binding
  packages/plugin-odoo/src/OdooImageDomObjectRenderer.ts
Labels: awaiting review

#221 [FIX] allow the main zone stretch vertically
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
Labels: needs refactoring

#224 [FIX] Core: refactor range selectedNodes to improve perf
  packages/core/src/VRange.ts
Labels: needs refactoring

#233 [IMP] OdooWebsiteEditor: add odoo field
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
  packages/bundle-odoo-website-editor/odoo-integration.ts
Labels: awaiting review

#236 [IMP] add a discard button in the menu for the odoo integration
  packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
  packages/plugin-odoo/src/Odoo.ts
  packages/plugin-toolbar/assets/Toolbar.css
Labels: awaiting review
