Repository odoo-dev/jabberwock, pull requests merged in 2020-02, with the labels that each got.

#79 [IMP] core: Add a keymap mechanism
  packages/core/src/EventManager.ts
  packages/core/src/JWEditor.ts
  packages/core/src/JWPlugin.ts
  packages/core/src/Keymap.ts
  packages/core/test/JWeditor.test.ts
  packages/core/test/Keymap.test.ts
  packages/plugin-char/Char.ts
  packages/plugin-list/List.ts
  packages/utils/src/testUtils.ts
Labels: wip

#102 [FIX] Format: properly toggle, keep attributes on heading change
  packages/core/src/JWEditor.ts
  packages/plugin-char/Char.ts
  packages/plugin-devtools/src/components/DevToolsComponent.ts
Labels: ready to merge... now!

#105 [FIX] DevTools: quickfix of problematic css
  packages/plugin-devtools/assets/DevTools.css
Labels: awaiting review
